version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
    volumes:
      - ./logs:/app/logs
    networks:
      - botnet
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  botnet:
    driver: bridge