version: '3.8'

services:
    qdrant:
        image: qdrant/qdrant:latest
        # environment:
        # - QDRANT__SERVICE__API_KEY=your_secret_api_key_here
        container_name: qdrant
        ports:
            - '6333:6333' # REST API
            - '6334:6334' # gRPC API
        volumes:
            - qdrant_data:/qdrant/storage
        restart: unless-stopped

volumes:
    qdrant_data:
